### ISSUE TITLE
SyntaxError: test.js: "result" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.)

### ISSUE THREAD

**Issue by mfn** [59naga/babel-plugin-add-module-exports#18]
I deduced this from working code; I know that it absolutely makes no sense in isolation but it triggers this transformation error. I *think* it has to do with this plugin, because otherwise I wouldn't be able to use the `export default` syntax.

```JS
'use strict';

export default function() {
  controller.get('/', async (res, next) => {
    const result = await someFunc();
    res.send(result);
    return next();
  });
}
```
Running with `node_modules/.bin/babel-node test.js`, results in
```
$ node_modules/.bin/babel-node test.js
/testproject/node_modules/babel-core/lib/transformation/file/index.js:540
      throw err;
      ^

SyntaxError: /testproject/test.js: "result" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.)
   1 | 'use strict';
   2 |
   3 | export default function() {
   4 |   controller.get('/', async (res, next) => {
   5 |     const result = await someFunc();
   6 |     res.send(result);
   7 |     return next();
   8 |   });
   9 | }
  10 |
    at File.buildCodeFrameError (/testproject/node_modules/babel-core/lib/transformation/file/index.js:407:15)
    at NodePath.buildCodeFrameError (/testproject/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:148:26)
    at PluginPass.Scope (/testproject/node_modules/babel-preset-es2015/node_modules/babel-plugin-check-es2015-constants/lib/index.js:33:29)
    at PluginPass.newFn (/testproject/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:309:17)
    at newFn (/testproject/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:276:19)
    at NodePath._call (/testproject/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/testproject/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/testproject/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/testproject/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitMultiple (/testproject/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (/testproject/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:195:19)
```
Using these packages:
```JSON
    "babel-cli": "^6.2.0",
    "babel-core": "^6.2.1",
    "babel-plugin-add-module-exports": "^0.1.1",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-stage-0": "^6.1.18",
 ```
and this `.babelrc`:
```
{
  "presets": [
    "es2015",
    "stage-0",
  ],
  "plugins": [
    "add-module-exports",
  ]
}
```
Changing the code to either `module.exports = ` or use `let` instead of `const` makes it work.

**Comment by lijunle** [comment]
I don't think the issue is related to this plugin. See this: https://phabricator.babeljs.io/T2892

**Comment by mfn** [comment]
You're right, it isn't related to the plugin; the referenced issue matches it already. I apologize for the noise!
