### ISSUE TITLE
TypeError: Cannot assign to read only property 'exports' of start

### ISSUE THREAD

**Issue by ChrisCinelli** [59naga/babel-plugin-add-module-exports#24]
I am getting

```
/tools/run.js:63
module.exports = exports['default'];
               ^

TypeError: Cannot assign to read only property 'exports' of start
    at Object.<anonymous> (run.js:29:16)
    at Module._compile (module.js:435:26)
```

In `start.js,` I have:
`import run from './run';`

In `run.js` line 29:
`export default run;`

**Comment by jasonmendes** [comment]
Did you figure this out? Is `tools/run.js` a transpiled file as well?

**Comment by ChrisCinelli** [comment]
I end up not using this plug in.
I started moving as much as possible to `import` and explicitly using `default` when I want to keep `require`.

**Comment by jdalton** [comment]
Is this still an issue?
