### ISSUE TITLE
Standard Code Style

### ISSUE THREAD

**Issue by lijunle** [59naga/babel-plugin-add-module-exports#5]
OK, let me open another issue to discuss this issue.

First of all, the current code is failing on lint.

Here is the result of `npm run lint`:

```
lijunle@arch [11:55:46] [~/Repos/babel-plugin-add-module-exports] [master *]
-> % npm run lint

> babel-plugin-add-module-exports@0.0.4 lint /home/lijunle/Repos/babel-plugin-add-module-exports
> eslint lib test

module.js:339
    throw err;
    ^

Error: Cannot find module 'eslint-plugin-mocha'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/lijunle/Repos/babel-plugin-add-module-exports/node_modules/eslint/lib/cli-engine.js:124:26
    at Array.forEach (native)
    at loadPlugins (/home/lijunle/Repos/babel-plugin-add-module-exports/node_modules/eslint/lib/cli-engine.js:115:21)
    at processText (/home/lijunle/Repos/babel-plugin-add-module-exports/node_modules/eslint/lib/cli-engine.js:202:5)
    at processFile (/home/lijunle/Repos/babel-plugin-add-module-exports/node_modules/eslint/lib/cli-engine.js:262:18)
    at executeOnFile (/home/lijunle/Repos/babel-plugin-add-module-exports/node_modules/eslint/lib/cli-engine.js:609:23)

npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "lint"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! babel-plugin-add-module-exports@0.0.4 lint: `eslint lib test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-plugin-add-module-exports@0.0.4 lint script 'eslint lib test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the babel-plugin-add-module-exports package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint lib test
npm ERR! You can get their info via:
npm ERR!     npm owner ls babel-plugin-add-module-exports
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lijunle/Repos/babel-plugin-add-module-exports/npm-debug.log
```

Secondly, I recommend you to install standard package as devDependencies. Not everyone want to install standard as global utility.

Last, please use the standard command line instead of `npm run lint` with `.eslintrc`, here is the result:

```
-> % ./node_modules/.bin/standard
standard: Use JavaScript Standard Style (https://github.com/feross/standard) 
  /home/lijunle/Repos/babel-plugin-add-module-exports/test/index.js:18:1: "describe" is not defined.
  /home/lijunle/Repos/babel-plugin-add-module-exports/test/index.js:21:3: "beforeEach" is not defined.
  /home/lijunle/Repos/babel-plugin-add-module-exports/test/index.js:30:3: "it" is not defined.
  /home/lijunle/Repos/babel-plugin-add-module-exports/test/index.js:42:3: "it" is not defined.
  /home/lijunle/Repos/babel-plugin-add-module-exports/test/index.js:50:19: Expected '===' and instead saw '=='.
  /home/lijunle/Repos/babel-plugin-add-module-exports/test/index.js:55:3: "it" is not defined.
  /home/lijunle/Repos/babel-plugin-add-module-exports/test/index.js:67:19: Expected '===' and instead saw '=='.
```

**Comment by 59naga** [comment]
thanks, This it can resolve quickly.

**Comment by lijunle** [comment]
Personally, I recommend [airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb). But however, It enforces the failing semicolon, which may be disliked by you.
