### ISSUE TITLE
[v0.3.0] cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by shreyasminocha** [59naga/babel-plugin-add-module-exports#58]
`.babelrc`:

```js
{
    "sourceMap": true,
    "presets": ["env"],
    "plugins": [
        ["transform-builtin-extend", {"globals": ["RegExp"]}],
        "add-module-exports",
        "transform-es2015-modules-umd"
    ],
    "moduleId": "VerEx"
}
```

```js
❯ babel index.js 
TypeError: index.js: Cannot read property 'name' of undefined
    at NodePath._getKey (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/family.js:148:23)
    at NodePath.get (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/family.js:138:17)
    at NodePath._getPattern (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/family.js:192:21)
    at NodePath.get (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/family.js:140:17)
  ⟶ at AssignmentExpression (/Users/shreyasminocha/dev/forks/repo/node_modules/babel-plugin-add-module-exports/lib/index.js:19:23)
    at NodePath._call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:108:19)
```

**Comment by ljharb** [comment]
I'm also seeing this on a number of modules where greenkeeper has tried to update the plugin.

Separately, it seems like v0.3.0 won't transpile `export default foo` to `module.exports =`, based on "However, the plugin doesn't change the pure-esmodule" - its primary/sole purpose is to add module.exports to pure ES Modules. Am I missing something?

**Comment by shreyasminocha** [comment]
@ljharb 

> However, the plugin doesn't change the pure-esmodule. this plugin makes changes only when exists exports.default

My understanding is that they meant it wouldn't transpile `export foo` but would transpile `export default foo`.

Moreover, that line has been in the README since before v0.3.0.

**Comment by AgentME** [comment]
I'm having this issue too in https://github.com/AgentME/react-save-refs/pull/9. You can reproduce the issue but checking out the "greenkeeper/babel-plugin-add-module-exports-0.3.0" branch of react-save-refs, and then run `yarn`.

**Comment by 59naga** [comment]
It was a missing check of simple AssignmentExpression. The following will fail.
```js
let foo
foo = "default-entry" // TypeError: index.js: Cannot read property 'name' of undefined
export default foo
```
[On line 10 of the plugin](https://github.com/59naga/babel-plugin-add-module-exports/blob/v0.3.0/src/index.js#L10), access to the [undefined property of AST of 2nd line](https://astexplorer.net/#/gist/a26dff5642830feb39bc9f0ac33d94b8/5f64f70fac20fce9bdc0c3a2aa02590a94c20298). this issue is fixed soon.

**Comment by 59naga** [comment]
Applied it as `v0.3.1`.

**Comment by loganfsmyth** [comment]
@59naga FYI, you can reduce that code a bit if you want, to

```
if (path.get('left').matchesPattern("exports.default")) {
```

**Comment by 59naga** [comment]
Nice, I'll apply it
